### ISSUE TITLE
Renderer process file load -- very slow

### ISSUE THREAD

**Issue by jurepetrovic** [kitze/react-electron-example#14]
Hello, 

in one of the react subpages we load a txt file contents. 
Sometimes, not always, the file read callback comes very very late. 
Did you have any issue with that? 

It helps clicking through react pages. Then callback suddenly comes. 
Any idea what could cause that? 

Rgds, 
Jure

**Comment by fredcox** [comment]
I was using the highlight e with react-native-elements.

I changing tô native-base and highlighter no problem is Very fast.

So, no problem with highlighter, it was componente ui question.

Thank u.

**Comment by jurepetrovic** [comment]
Ok, I don't think we understand each other.
I tried to do readFile() inside React component of an electron app.
The readFile was executed instantaneously, but the callback needs ~40secs
to return.
Anyone had similar issues? Look at pic below.

[image: image.png]



V V tor., 9. jun. 2020 ob 12:32 je oseba Fred Cox <notifications@github.com>
napisala:

**Comment by jurepetrovic** [comment]
React and electron are maybe not very nice together. We used electron-router library at the end.
