### ISSUE TITLE
How to work with the Main electron's process?

### ISSUE THREAD

**Issue by mnemanja** [kitze/react-electron-example#4]
Hi Kitze,

Thanks a bunch for this nice guide. It works like a charm :)

I'm wondering if you have ideas how one would work with the electron's **main process** now that it's in public folder?

For example, I want to integrate an embedded **sqlite3** database, and it has to be accessed from the main process.

Also, would it be possible to see an output of a console from the main process? The `electron-dev` output seems static. Basically, a way to refresh the output for development and debugging?

**Comment by tboulis** [comment]
Add an sql.js file in your public folder where you initialize the [sql.js](https://github.com/kripken/sql.js/) npm library.
